import localFont from "next/font/local";
import "./globals.css";
import { languages } from '../i18n/settings'
import { dir } from 'i18next'

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export async function generateStaticParams() {
    return languages.map((lng) => ({ lng }))
}

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
    og_title: "Create Next App",
};

export default function RootLayout({
   children,
   params: {
       lng
   }
}) {
  return (
    <html lang={lng} dir={dir(lng)}>
    <head>
        <meta name="robots" content="index, follow" />
    </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
